### ISSUE TITLE
Separator Between Chords in measures_as_strings?

### ISSUE THREAD

**Issue by chigkim** [drs251/pyRealParser#1]
Is there a way to have a separator between chords when there are more than one chords in a measure? It just prints something line "F-7Bb7".
Can we have F-7 Bb7 or F-7,Bb7?

**Comment by drs251** [comment]
Sorry for taking so long to respond to this - I haven't thought about this project for some time. I will look into adding an option to put a space between two chords in the same measure.

**Comment by drs251** [comment]
I just made a small update that should solve this issue (it also fixes a few other bugs). I haven't made a package yet, but I'd be grateful if you could download pyRealParser.py and check if it's giving you the results you expect - I'll make a new package for pip as soon as I'm confident that all bugs have been fixed.

**Comment by chigkim** [comment]
Sorry for late response!
I did check, and it works as expected!
Thanks so much!
